#+STARTUP: showall
#+OPTIONS: toc:t
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+LANGUAGE: zh-CN
#+OPTIONS:   ^:{}
#+TITLE: 拿细耳人
#+TAGS: Ezra 
#+DATE: 2016-11-17

** 读经：民6：1-8
** 大纲：
*** 不可喝清浓酒 -- 远离属世的享受
*** 不可用刀剃头 -- 披戴基督的羞辱
*** 不可挨近死尸 -- 持守圣洁的地位
** 引言
刚才的读经解释了旧约拿细耳人的相关条例，这是神在旧约亲自向以色列百姓制定的祂想要的，按着祂的心意侍奉祂的人的要求。
那么请问，弟兄姊妹们，圣经里面有几位拿细耳人？（参孙、撒母耳、施洗约翰）。他们有不同的地方也有相同的地方；不同地方：参孙的恩赐在于力量，战胜仇敌；撒母耳的恩赐在于祷告，带领以色列人归向神（耶15：1）；施洗约翰的使命在于引人悔改，受洗。相同的地方：他们都在不同的时代里面肩负着不同的使命，并活出自己的意义与价值，成为神所记载的人物，留名与后世。
** 本论
*** 不可喝清浓酒 --远离属世的享受
【箴23:29-32:谁有祸患？谁有忧愁？谁有争斗？谁有哀叹（或作“怨言”）？谁无故受伤？谁眼目红赤？就是那流连饮酒，常去寻找调和酒的。酒发红，在杯中闪烁，你不可观看，虽然下咽舒畅，终久是咬你如蛇，刺你如毒蛇】。所属这世界的东西就是【眼目的情欲，肉体的情欲并今生的骄傲】（约一2：16），对于基督徒，尤其当代的年轻信徒来说，所面临的挑战是非常的大。一方面世界的酒是如此的好喝，又好看，又美味，而因为年轻，又学习于这个世界，生活于这个世界，无法胜过这个世界。另一方面还要承接并持守上一代长辈所留下来的基业，但生命幼小，试探较大，对于神的话语和生命的经历又浅又少。甚至有的时候对于基督的爱情和生命的长进都比较麻木。更喜欢那发红的美酒，并且极力的想去喝上一口。但当喝上去的时候，就会被牠所辖制，偷去你的生命，没有力量争战，就像参孙一样。
最近几年，衣服做的越来越暴露，上衣做的越来越低，裙子做的越来越短，是个男人都忍不住想看一眼，激起你情欲的火。小弟兄在大学的时候也无法胜过，最后想到一个办法，在校园里走路的时候把眼镜去掉。因为小弟兄眼镜近视400多度，去了眼镜，有一天，我室友迎面走来给我打招呼我都没有认出来，那个距离已经相当近了。更不要说那些长腿偶巴，怎么在校园里面风骚的走位，对于我来说都是浮云。我惹不起，我还躲不起么。面对这些，我们基督徒要学会逃。
好像人活在世界上这几十年无非为了满足肉身的喜好.肉身喜欢看电影，电影的特效和剧情就越设计越逼真，越刺激，越吸引人；肉身喜欢吃好的，世界就给你罗列着各地的美食；肉身喜欢追求上档次的事物，世界就会把这些档次的东西展现到你面前。当然我不是说弟兄姊妹就不去看电影，不去吃好吃的，不要有追求。神给我们创造这世界，就是要我们管理，享受。但凡事都可行，但不都有益处。当你在读经，祷告，学习的时候，突然肉体说：上次HBO的《西部世界》又更新了或者说老余杭新开了一家小火锅，灰常好吃。这时候，你是否愿意放下正在读的圣经，祷告是否还能正常？一个真正的拿细耳人知道自己走了这条路，所有的一切都不是凭着自己所喜好的去行，乃是要问问主，这是否可行。保罗是攻克己身，叫身服他。以主的事为重，我尊主为大，灵就必快乐。求神来帮助我们，当我们遇到这些事情的时候，也能够有合适的应对。
我们知道宇宙的原罪便是骄傲。世界上的人以为挣了钱，那便可以随意。因为俗话说有钱能使鬼推磨，但小弟兄说有钱能使磨推鬼更合适一些。他们看自己是高人一等，看别人都是武大郎；穿金带银于一身，瞧不起像我这样像农民工的土鳖，据说魔都的土著居民是这样的，瞧不起外地人。在全国河南人最受人不待见，殊不知在永恒面前，我们都算不上什么。但不光世界上的人有骄傲，在主内也有。比如说此刻站讲台的小弟兄。辛辛苦苦准备了一篇讲章，花了很长时间祷告，读经，查考资料。就想着会后就会有不少的弟兄姊妹说你讲的真好哇。这时候，一不小心就会窃取神的荣耀。事实上，我们只不过是一个瓦器，如果宝贝不放在里面，我们什么都不是。所以，小弟兄有这么一个祷告，求你保守，不让孩子偷取你的荣耀。求神来恩待我们，让我们能有这个认识。
提后2：22节你要逃避那少年人的私欲,同那清心祷告主的人，一同追求公义，信德，仁爱，和平。小弟兄最喜欢过的生活就是夏令营，冬令营。大家住在一起，每天早早的起床，有长辈的弟兄姊妹打扫卫生，饭食服侍，祷告服侍。在聚会当中，又有讲道恩赐的弟兄讲解神的话语。聚会后，又一起交通，一起祷告，一起生命的长进。结束后，回到学校里面，弟兄姊妹又一起勉励，鼓励，装备。在这种生活当中，跟神的关系很近，神的同在让人很享受，都没有想着去犯罪的念头。这就说明一个基督徒必须常常聚会，有一个属灵的同伴，过团契、教会的生活是多么的重要。因为活在教会里面，就是保护自己的生命。
*** 不可用刀剃头 -- 披戴基督的羞辱 
【林前11：14】男人留长发是不荣耀的，是羞辱的。【赛53：2】祂在耶和华面前生长如嫩芽，像根出于干地。他无佳形美容，我们看见祂的时候，也无美貌使我们羡慕祂。
我认识很多的基督徒，信了耶稣很多年，在众人面前不敢承认自己是信耶稣的，怕丢人；不敢在吃饭的时候祷告，怕别人问他说你是信耶稣的？包括小弟兄也在内，之前在学校，吃饭的时候都是在吃饭的路上早早的祷告好，打好饭，然后直接开吃。后来，小弟兄认识到这是不对的，如果我不在众人面前认主，主必定不会认我。所以找工作，一定会给老板讲公司里面是否接纳信耶稣的，因为我是信耶稣的。入职后，同事一起吃饭，我就会当着大家的面祷告，大家都过来问，然后我就给他们讲耶稣的事情。别人从来没有说，信耶稣的人怎么不好或者信耶稣怎么不好，脑子抽了，进水了之类的话，或者逼视你这个人，反而都带着一些问题来，我呢就很热心的去解答，后来甚至有的同事提出看圣经，带着他去聚会，超乎我的想象。弟兄姊妹，我们只是被那个怕羞辱的观念所影响，被那个惧怕蒙了双眼，而当我们真正走出这一步的时候，你会发现真的一点都不难，并且会引人归主。
基督徒面对的挑战会越来越大 ，越来越多。也许今天只是干涉我们聚会，但明天也许就会像解放初期的逼迫一样,不少的长辈弟兄都为了主的名坐监，受刑，做苦工，甚于为了信仰舍弃了自己的性命。但现在的90后和00后不得不让我们有一些担心，教会的传承能否延续，未来当真的遇到主耶稣在马太福音24章里面说的大灾难的时候，我们这些年轻人能否继续持守自己的信仰，披戴基督的羞辱，就像【来11：26】里面所说摩西【他看为基督的凌辱比埃及的财物更宝贵，因他想望所要得的赏赐】.愿神来恩待教会里面的年轻人，也恩待长辈的弟兄姊妹，使我们都能够在这末后的时代里面持守真道，看基督的羞辱比万物都宝贵。
*** 不可挨近死尸 -- 持守圣洁的地位
旧约圣经里面两次提到【你们要圣洁，因为我是圣洁的】（利11：44-45）
对于小弟兄来说这个圣洁真的太难了，无数次的挣扎，无数次的反复都无济于事。正活在罗马书【7:18  我也知道在我里头，就是我肉体之中，没有良善。因为立志行善由得我，只是行出来由不得我】。多少次失败又继续立志，我发誓再怎么样就怎么怎么样，可是当你失败的时候，主啊，我又错了，又得罪你了。后来我才明白过来，一方面，我们永远带着罪性，罪人的身份就是去犯罪，不管立志多少次，你还是去犯罪，立志是没有用处的；另一方面，原来对于罪恶我已经是一个死人了，当主耶稣在十字架上的时候，已经将我这个败坏的生命，老我的生命和一切的邪情私欲都同钉了十字架。现在活着的不再是那个之前的我，而是基督的新的生命在我里面活。当我遇到罪恶试探的时候，我就知道，我已经是一个死人了，这些东西对我没有吸引力了。
感谢主，现在当我遇到这些试探的时候，我就会有这个意识，啊，我已经是一个死人了，死人还会去做这些事情么？但是里面还会有罪性在发动，去让你犯罪，不是没有，是会有的。真的需要主来帮忙，转向主。因为我们是在祂的里面，祂必负我们完全的责任。若偶尔被过犯所胜，感谢主，主的宝血可以洗去我们的罪。但那些故意犯罪的，赎罪的祭就没有了【来10：26】
** 结论
小弟兄今天从拿细耳人的条例给弟兄姐妹们分享一些自己在主的道路上面的一些心得。这条路虽然又窄又崎岖，但主已经为我们走过。虽然世界如此的吸引人，但我们可以选择逃离；虽然基督是羞辱的，但地位却是荣耀的；虽然圣洁是那么的难持守，但活着的不再是我。求神来帮助我们，趁着年轻记念造我们的主，趁着还有时日来装备自己，趁着还能走得动来侍奉我们的神。荣耀归给祂！
