#+STARTUP: showall
#+OPTIONS: toc:t
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+LANGUAGE: zh-CN
#+OPTIONS:   ^:{}
#+TITLE: 认识自己的地位 
#+TAGS: Ezra 
#+DATE: 2016-11-13

** 大纲 
*** 题目： 认识自己的地位
*** 经文： 彼前2：9节【惟有你们是被拣选的族类，是有君尊的祭司，是圣洁的国度，是属神的子民。要叫你们宣扬那召你们出黑暗入奇妙光明者的美德】
【But you are a chosen people, a royal priesthood, a holy nation, a people belonging to God, that you may declare the praises of him who called you out of darkness into his wonderful light.】
*** 结构：
**** 罪人的地位 -- 无可傲娇
**** 祭司的地位 -- 完全奉献  
**** 圣洁的地位 -- 无可污秽
**** 儿女的地位 -- 活出样式 
** 内容
*** 引言
*** 本论
**** 罪人的地位
【你们得救是本乎恩，也因着信。这并不是出于自己，乃是神所赐的。也不是出于行为，免得有人自夸】-- 弗2：8
我们都会祷告说：谢谢天父，在创世之前已经拣选了我们。但我们应该知道，这一切都是神为我们做成的。并不是因为我多么的好，并不是说我信耶稣是给耶稣面子，也不是说是我自己拣选了信仰。
其实我们说，主啊，我信你，这句话都是神先将信的心志放在我们的里边，然后我们才说出来的，否则我们就会像世人一样说：那只不过是一种信仰的寄托，耶稣只是一个非常好的现实人物而已，或者说那只不过是一个迷信，我什么也不信。如果信不是神所赐的，我们不会相信的。
我们得救不是说，我信耶稣，是因为我是多么好的一个人，在大家面前口碑很好，人品很好。我捐了多少的钱，我行了多少的善。这些都是神的恩典，若不是神宽容你我，今天你我早已在黑暗里面了。
神亲自差遣祂的儿子来到世上，耶稣亲自为我们从高天来到地上，亲自为我们降生在马槽当中，亲自经历人世间的苦难，又为我们医病，赶鬼，亲自为我们受鞭伤，受刑罚，亲自为我们背上沉重的十字架，亲自将我们全世界罪人的罪恶都归到祂的身上，神亲自使祂的儿子从死里复活，神又将相信的信放在我们的心里，又差遣圣灵住在我们的心里；我们什么都没有作，这都是白白的恩典。
**** 祭司的地位
**** 圣洁的地位
【那召你们的既是圣洁、你们在一切所行的事上也要圣洁。因为经上记着说：你们要圣洁，因为我是圣洁的。】-- 彼前1：15-16
对于一个大学生来说，面临着时代的挑战是非常的大。小弟兄大学四年的生活很糟糕。游戏，打牌，喝酒，色情样样都来，如果你不与他们一起，就被他们看成另类。如果你和他们一起，你的良心就被仇敌所控告。有的时候，你无法克制自己的肉体出来的意念。无法过一个圣洁的生活，无法成为一个贵重的器皿。
这也是当代的信徒与老一辈的信徒的差异。老一辈的信徒愿意为主受苦，坐监，甚至拿出生命来捍卫自己的信仰。但仇敌发现，这无法信仰灭亡，只能让信仰更加的坚定，更加的纯正。牠借着互联网，游戏，视频，音频等，换着法子来破坏神的教会，甚至有的时候是我们自己主动去找牠。
但感谢主，弟兄姊妹，我们信耶稣的那一刻起，我们老我的生命就已经与基督同钉十字架，我们里面的生命乃是基督的生命，是一个新的生命。神将我们这些信而爱浸的罪人都放在祂儿子的里面。我们需要常常信靠神，我们是在基督的里面，我们也要知道我们对世界而论，我们是一个已经死亡的人。死人是不会犯罪的。感谢主，当小孩子再次面对那些试探的时候，懂得怎么样去胜过，不是靠着我们的意志，不是靠着我们的力量，乃是靠着主，住在基督里。
**** 儿女的地位

*** 结论


