#+STARTUP: showall
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+LANGUAGE: zh-CN
#+OPTIONS:   ^:{}
#+TITLE: 七月份作业
#+TAGS: 
#+DATE: 2016-09-05


** 以撒生平总结  
*** 一生年日
- 0岁--应许出生
- 8天--受割礼
- 童子--活祭献上
- 36岁--母亲去世（127-91）
- 40岁--美好婚姻
- 60岁--得添双子
- 75岁--父亲去世（175-100）
- 耕种、挖井经历神
- 晚年祝福
- 180岁--安然见主 
*** 一生行径
- 起点：出生于基拉耳（创20：1）
- 基拉耳 --> 别是巴 （创21：32-34）
- 别是巴 --> 摩利亚地（创22：2）
- 摩利亚地 --> 别是巴（献祭完成，回家）
- 别是巴 --> 希伯仑（创23:2）
- 希伯仑 --> 庇耳拉海莱（创24：62）
- 庇耳拉海莱 --> 希伯仑（创25：7-9，埋葬父亲）
- 希伯仑 --> 庇耳拉海莱（创25：11，埋葬父亲完成，就住在这里）
- 庇耳拉海莱 --> 基拉耳（创26：6）
- 基拉耳 --> 利河伯（创26：22）
- 利河伯 --> 别是巴（创26：23）
- 终点：别是巴 --> 希伯仑（创35：27-28）
*** 一生总结 
**** 父母同在的人生
***** 应许出生
- 第一次（创15：4），这时亚伯拉罕并子嗣，以为大马士革人以利以谢是他的继承人；
- 第二次（创17：15-22），当亚伯拉罕因听众妻子的话，动了情欲，生了以实马利，神13年之久没有向他显现。当他99岁的时候，神给他和妻子改名，同时赐下割礼的记号。重新再坚固应许之约。这时亚伯拉罕以为以实玛利就是他的继承人
- 第三次（创18：10-14）神在毁灭所多玛之前，重新应许撒拉生一个儿子
***** 丰富之子
- 亚伯拉罕将一切都给了以撒（25:6）
- 神将与亚伯拉罕的约坚定与他（26:3-4）
***** 顺服之子
- 摩利亚山的奉献
- 得美好的婚姻
- 得百倍的收成
**** 与神同在的人生
***** 独自面对仇敌
- 当父亲的井被仇敌塞住的时候，他作恢复的工作
***** 真实地经历神 
- 埃色：他认识到肉体的律与属灵的律在相争，交战。靠着自己无法胜过
- 西提拿：他认识到仇敌，自己需要逃到神的里面
- 利河泊：他认识到在神那里有无尽的丰富
- 别是巴：他认识到与神同在是好的无比
***** 晚年祝福
将从神那里应许的祝福赐于神所喜悦的人
**** 人与神的评价
- 神与他同在（创26：28：我们明明地看见耶和华与你同在.....)
- 寄居在希伯仑（创25：27）

** 马太福音11：20-31节
*** 分段考虑：
- 第一段：太v20-24：主耶稣用对比的形式来责备那些不愿意信祂的人
- 第二段：太v25-31：主耶稣向父神的祷告
*** 每节理解
**** v20：耶稣行了那么多的神迹奇事来证明祂是的神的儿子，无奈这些城里面有的终不悔改。
**** v21-24： 
这里面列了五个城，五个城的结局都不好，有的被灭，有的成为废墟，有的已经不存在
***** 推罗
****** 圣经关于推罗的预言
- 赛23章
- 耶25章、27章、47章
- 结26章、27章
- 珥3章
- 摩1章
- 亚9章
****** 现实中的历史
 大约於公元前五百九十多年，神藉先知以西结向推罗发豫言，要惩罚毁灭推罗。推罗城是面临地中海的海港名城。那里居住的人原来都是腓尼基人，他们以行商、航海而闻世。是古代商业中心之一。当其正强盛时，行事霸道，罪恶甚大，神曾藉众先知的口警告过(如阿摩司、约珥、耶利米等都曾经豫言过，但没有以西结豫言之详细)，但仍未见悔改，神就藉先知以西结豫言推罗应受之惩罚。豫言发出不久，於公元前五百八十六年巴比伦王尼布甲尼撒，率军围困推罗城，经过十叁年之久的战争， 得攻陷该城。後来这个战争的经过，被拍成电影「木马屠城记」，成为举世皆知的故事。推罗王於尚未陷城之前，将其财宝迁移到离旧城一公里多远的对面海岛之上。尼布甲尼撒王的军队进城之後一无所得，愤将该城完全拆毁，如此应验了豫言的前面一段。

 推罗城被攻陷後大约经过了二百四十年，废墟依然存在，豫言的後半段仍待考验之中。正在那时，希腊的亚历山大皇帝抬头，征服各地，威名震动远近。他於公元前约叁百叁十二年时，挥兵进攻推罗城。那时推罗的人已经在海岛上建立了新城。亚历山大下通牒给推罗人，要他们开城投降。但是推罗人认为他们的城建在海岛上，在没有军舰、火炮之古时，敌人不易渡过急潮流来到岛上攻城，据天险而守，是难攻不落之要塞，所以就拒绝投降。但是亚历山大实在是非常杰出的军事天才，且有非常坚强的意志，不因遇难就半途而废。他为要攻下新城，下令修 石堤，自大陆直达岛上。因为工程钜大，不祗把旧城的木头石头都抛到海里填海，且把旧城及附近的泥土刮净，终於修 海堤。然後由这条临时构成的海堤道路挥大军进逼城下，攻陷新推罗城。豫言的第二段部分∶「石头、木头、尘土都要抛在水中」，「刮净尘土」等的话，就如此得着应验了。至於最末段的豫言，「使它成为净光的磐石，它必在海中作晒网的地方...不得再被建造。」是怎麽应验的呢？事情的经过是这样∶旧城的废址，因地面上的尘土(也就是粘土部分)被刮净，沙层的部分，经年被雨水冲洗，不久就显出基层的磐石，如今真的成为渔夫晒网的地方了。至於不得再建造一节，更是难以应验，因为这样的豫言似乎太冒险了。一个城市将要被毁灭是可以说的，但怎麽可以说「不得再被建造」呢？我们都知道罗马城比推罗城大得多，只因为暴君尼罗王，为要吟好诗，得诗人的称赞，为寻求灵感，异想天开，下令烧毁全城，但是罗马城不久之後又被重建起来，而且规模比旧城还要大、还要宏伟。尤其科学发达，建 技术，机器齐全的近代，可以移山填海，即是沼泽海地也能以短期间内变为现代化都市。美国华盛顿的郎维郁城就是最好的证明。推罗的旧址，本是很适宜於居住。因为那里有一泉源，每日可以涌出一千万加仑的淡水，供为饮水。且附近有肥沃的田地，一直伸展到遥远的山边。但是自从推罗城被毁之後，已经历将近二千六百年，该城一直未被重建。当然这一切都是在神主宰手下。祗要推罗是处在绝对荒废的情况中，无可否认的，以西结的豫言是出於神而已完全应验，叫人无可推诿。
***** 西顿
****** 关于西顿的预言
- 赛23章
- 耶25章、27章、47章
- 结27章、28章、32章
- 珥3章
- 亚9章
****** 西顿的历史 
西顿位於推罗的北方约二十英里之处，是腓尼基人重要海港城市。把巴力(太阳神)及亚斯他录(月神)等偶像带给以色列人，败坏以色列国的耶洗别王后就是西顿王谒巴力之女(王上十六31)。西顿人也常加害以色列民，罪恶甚大。所以神藉先知以赛亚(赛廿叁4)，约珥(珥叁4)警告过他们，但是未见悔改。故藉先知以西结发出上述的豫言，要惩罚西顿。但是这个豫言和惩罚推罗的豫言大不相同。在这个惩罚里，没有要毁灭西顿的话，更没有不得再建立等的话。虽然如此，西顿也受了很大的痛苦，西顿数百年间屡遭灾祸，这种长久的历史，足以证明豫言所定的惩罚完全应验。在巴比伦王尼布甲尼撒的时候，受了一次兵灾，归属於巴比伦统治，几十年後又被波斯王古列攻打，改隶属於波斯。後来他们叛变，波斯军就围攻了西顿。根据历史的记载∶「援救绝望，四万居民誓死不降，相率自焚其屋，老幼男女尽死火中」等语。西顿的遭遇并不停於此，再过了数百年之後在十字军东征的时期，西顿又屡次被攻陷，叁次被掳於十字军，又有叁次败给回教军，且每一次兵灾都带来瘟疫，西顿人不是死於刀剑就是死於瘟疫。如此应验了「我必使瘟疫进入西顿，使血流在它街上；被杀的必在其中仆倒，四围有刀剑临到它」的豫言了。并且就是到了近代，对於西顿的惩罚尚未结束；考德鲁司(Druses)与土耳其的战争，土耳其与法国的战争，都以西顿为战场，一八四○年又被英、法、土叁国的舰队炮击，实在是「四围有刀剑临到它」。然而今天西顿还在那里，因为在豫言里并不像对推罗所说的，「毁灭及不得再被建立」等话语。所以西顿的遭遇及西顿的存在都是证明豫言是准确的，是出於神的。
***** 所多玛
****** 关于所多玛的经文
- 创18-19章
***** 哥拉汛、伯赛大、迦百农
****** 哥拉汛的历史
大约在公元前400年左右，一次大地震毁灭了迦百农、伯赛大、哥拉汛。他们是加利利湖边的几个村庄。马太福音、路加福音里面两处都记载着主预言他们的结局。

#+BEGIN_SRC shell
 ？ 为什么拿哥拉汛、伯赛大与推罗、西顿对比；迦百农与所多玛对比
#+END_SRC
***** 经验教训
- 万事都在神的手中，神是忌邪的神，祂不容忍罪恶，祂也不喜欢骄傲。不管我们行的多么好，若不信神都是枉然。
- 我们应该汲取历史的教训，从这几个城的结局看到神的心意，祂巴不得我们相信得救，我们不可硬着颈项
- 当神一次又一次的怜悯恩待我们，一次一次的向我们施恩的时候，我们不可置祂的恩典于不顾
**** v25-30
- 天父的旨意向单纯的婴儿显现。我们若不谦卑像小孩子一样，断不能进神的国。人的聪明与智慧都无法知道神的事，因为祂的意念高于我们的意念
- 我们若不在基督里面，我们就不会认识天父，因为父将所有一切的丰富都藏在基督里面
- 主是我们安息的所在，我们要学会将劳苦重担交给主，让祂来成为我们的一切
- 当我们学习基督的谦卑、顺服，愿意走十字架的道路时，我们就得着了安息。因主断不会将过重的担子交给我们，总会给我们开一条出路
