#+STARTUP: showall
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+LANGUAGE: zh-CN
#+OPTIONS:   ^:{}
#+TITLE:劳工节特会：基督是一切，又在一切之内（Bro Ernest W.） 
#+TAGS: 
#+DATE: 2016-10-22


**** 诗篇第一篇

[昼夜思想耶和华的律法，这人便为有福；他要像一棵树栽在溪水旁，按时候结果子，叶子也不枯干。]

1. 这棵树被栽在溪水旁是因为他昼夜思想耶和华的律法，深刻的认识与主的同在
2. 他是栽在溪水旁，而不是像动物那样，只有渴的时候才来到溪水旁。他就是在溪水旁，时刻从水那里汲取力量，不会干渴。
   - 巴不得整天都在基督里，不会干渴
   - 更渴望有更深的与基督交通的生命，不被其他的事情所干扰

**** 活着就是基督

保罗讲：他活着就是基督，他死了就有益处。

不得不讲，这句话是非常难讲，并且难以到达的地方。
基督的生命进到我们里面的时候，我们得了一点点就非常的满足，就以为自己多么的了不起。以为自己就得着了，其实不然，我们只不过得到了一点点，还没有得到基督的一切。
因为基督是一切，又在一切之内。祂是一切，我们只得到了一切的一点点而已。

保罗讲的这句话，基督已经在祂里面，祂就是一切，住在他里面，他也就是基督。

这句话是多么的重，也可以看到保罗对主的认识是多么的深入，与主的关系是多么的近。


**** 磐石出水

当以色列民因没有水发怨言的时候，如果是我们，我们会怎么做？我们会反问说？

也许我们会说：我这里有几瓶脉动，但也只能够满足几个人的需要；
也许我们会说：我这里没有水，给不了你们水
也许我们会像摩西那样，自己没有办法，只有去神的面前求水。

但这一切都没有什么，当我们得到神的答案的时候我们是否可以顺服的去做？用杖击打磐石出水

我们可能会说：这根本不可能，你在开玩笑么？这样作，如果磐石不出水，肯定会被以色列人用石头打死的。

我们面对问题的时候，我们有的时候根本不会想到去神面前去求问；
或许我们会到神面前去求问，当神给我们答案的时候，我们是否会接受？

祂没有让你像何西阿那样娶妓女为妻；
祂没有让你像约伯那样经历家破人亡的经历；
更没有让我们经历在地震，缺水，饥饿等恶劣的生存环境当中。

感谢主，顺服好像变得更加容易接受了。



