#+STARTUP: showall
#+OPTIONS: toc:t
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+LANGUAGE: zh-CN
#+OPTIONS:   ^:{}
#+TITLE: 主日感恩聚会
#+TAGS: LoadsDay
#+DATE: 2016-12-11

*** 田东辉弟兄
- 刚开始信耶稣的目的就是为了让孩子上主日的学校
- 见证自己是如何去信耶稣的，一方面是由于拉不下面子，看着别人过来，不好意思不见；另一方面怕对孩子不好；
- 来聚会，犯困，上午讲的东西不太容易接受，下午有生活的实际，有一些得着
- 信主后，日常的生活、工作、态度都发生了变化；由一个飙车的司机，现在有人加塞的话，知道谦让；之前还会骂人，现在不骂人了；与同事的态度也好转了起来。
- 当你真心的去信之后，生命发生了改变，父母，兄长，国家都改变不了你的品性；
- 从孩子去上学半个月不聚会，觉得心里空当当的；自己和姊妹虽然不是聚会，但来到聚会的地方和倪姊妹交通，回去睡的非常的好；
- 自己对信望爱福的认识，信像根，望像干，爱是花，福是果；敬畏的心和感恩的心就像阳光和雨露；
- 现在认识到，信耶稣不是信仰，而是接受基督的生命。信耶稣与其他的信仰不一样，不是修行，那些是门外汉；
*** 刘玉敏姊妹
- 去年感恩姊妹没有感到神的大爱，而是看到人的本事
- 交通孩子的难处：成绩差，没有考学的出路，高的考不上，低的不想去。传福音的姊妹的孩子在东北的基督学校上学，不用考虑，但是条件就是信耶稣，所以就来信耶稣了。
- 因为自己是一个多愁的人，有一些内向，没有主见，自己的孩子也有一些内向。信耶稣之后认识到敬畏耶和华是智慧的开端，而不是依靠口才。
- 信耶稣之后，主就立刻吸引，刚开始来聚会觉得没有意思，不想呆了，然后就撒谎说公司有事，并跟儿子讲聚会取消了，大家去骑车去了。
- 信耶稣之前看小说是自己最大的爱好，传福音的姊妹说你信耶稣之后你就再也看不进去小说了，刚开始的时候不信， 后来就开始坚持读经群里面的读经。在工作的时候，还是看小说，但是看小说的手机看20分钟就黑屏，还是苹果手机。后来就把自己电子产品里面的小说都给删除掉，然后不看小说，看看圣经，唱唱诗歌（虽然跑调），看看弟兄们分享的东西。
- 与孩子打电话的时候鼓励他读经，祷告，睡不着觉也要祷告，遇到仇敌要祷告。孩子说现在在看荒漠甘泉，知道一些不好的事物都是仇敌做的。学校里面要上交手机，别人都是买一个破手机然后上交上去，自己却诚实的把手机交了上去。
- 信耶稣之前，弟兄晚上下班回来晚，担心出事故；信耶稣之后，知道这是仇敌的搅扰，然后祷告主，就很平安。
- 自己是一个不顺服的人，看弟兄不读经就会很烦；看见自己之前也是一点点成长起来的，现在夫妻之间坐下来就讲讲彼此哪件事没有做好，大家都去改正。
- 也非常的感恩，受浸之前都有栽培，受浸之后的成长都是其他的弟兄姊妹来支持。
*** 周晓楠姊妹
- 去年牌楼小家因为拆迁，将岸上蓝山的房子装修一下，从牌楼来这边公交车不诠，因为闲林小家离自己最近就来到这里聚会了。来闲林之前，樊弟兄和老姊妹都嘱托要帮帮倪姊妹，倪姊妹很辛苦。
- 来闲林小家之后，看到弟兄姊妹彼此相爱， 牌楼小家装修好之后，弟兄姊妹可以回去聚会，自己就很矛盾是否离开闲林回牌楼聚会，后来决定留在闲林，但住在牌楼。牌楼的弟兄姊妹邀请回牌楼，但自己说闲林小家有负担，不想离开。
- 来闲林小家之前，不看圣经，也不祷告，之前有老弟兄讲：你要看圣经，凡事也要祷告。来之后参加闲林的读经小组，每天坚持读经。现在读经有一些不懂的地方，一遍一遍的看，看懂为止
- 因着幼儿园的伙房工作，想跟着一个年轻的理发师学理发，但是自己丈夫不支持；自己去理发店里面去学习，丈夫就去理发店里面吵；跟弟兄姊妹们交通，弟兄交通要顺服丈夫，但是自己因为不好意思再回幼儿园，但是没有办法，所以就去找幼儿园园长说自己想回幼儿园工作，园长立马来电话说同意。因着顺服带来了一次出路。
*** 史慧芬姊妹
- 20岁左右的时候妈妈信主，妈妈叫自己去聚会，但自己不想去；当自己去教会里面的时候，屁股也痛，全身都不舒服，也很累。最多就去了三四次。
- 结婚之后，遇到了难处，自己妈妈信耶稣，自己也不去求告别的神，当时自己儿子只有4、5岁。当时的工作很辛苦，不上班在家带小家，带了半年，全都靠着丈夫上班来养活全家。家里面有一些紧缺，自己就去做生意，自己因为没有本钱，问自己的哥哥借了一万块钱，去城站那边开店，做了半年亏掉了。哥哥鼓励积累一下经验，慢慢做。因着自己贪玩，就把自己的生意交给旁边的人帮忙看店，自己去游泳。年底，一万块钱全都亏了，自己不做了。就去找妈妈说这个事情，自己借了哥哥的钱，但是还不出来，妈妈去找哥哥求情，哥哥也答应说有了就还，没有就不用还了，所以自己就没有还。第二年，儿子6岁的时候要去读书，要用钱，哥哥在宁波开了一家舞厅，装修花了四十万，请小弟兄们管理，打电话给哥哥，想在哥哥那里找一份工作。于是儿子6岁的时候就过去了，大半年后，儿子7岁在杭州读书，丈夫每天都非常的忙碌，丈夫去赌博，每天都是最后一个去接儿子。就将儿子带到宁波去读书。后来哥哥把舞厅转给了别人。自己就回了杭州。自己在宁波的时候，妈妈去聚会，自己又没去，就在妈妈家里的十字架下面祷告，然后就第一次在那里祷告，求神救救自己的一家，如果主你次帮我，我以后总会要你的。神是很奇妙，就听了祷告。后来回到了杭州，自己在杭州呆了半个月之后，丈夫让自己去做丈夫单位的工作，丈夫去饭店里面打工。但是自己没有去聚会，在丈夫的单位上班了两年，丈夫在饭店也打工了两年，收益很好，神亲自来祝福。但此时却没有去信耶稣。
- 丈夫后来有一次与顾客吵架，丈夫就不做了，又回到之前的单位上班，自己就失业了。这时候想起来，神祝福了但是没有去信耶稣，就给妈妈打电话说自己要信耶稣了，妈妈很高兴。因为主帮了自己，所以自己就要去信耶稣。然后妈妈就为自己找聚会的地方，就去了龙家桥，第一次去了之后，然后就联系一了范姊妹，然后范姊妹带着自己去了古荡。但是在古荡聚会的时间还没有在闲林聚会的一年时间长，经常不去聚会。再后来又上班，礼拜天没有休息，也就不去聚会了。想着自己信主，反正已经信了，就完成任务了，并且聚会时间长，礼拜天没有休息，又要做家务，又要带小孩子，太忙了，发一些怨言，信主太难了，时间忙不过来，聚会时间又太长了，去了也是不甘心。然后6月份受浸就直接糊涂的受洗了，自己连受洗是什么意思都不知道，想着你们都受洗了，我也受洗就好了。后来又活到埋怨的光景，有事情就不去聚会。一不去就是好几年。
- 儿子结婚了，娶的妻子也非常的不错。想着自己不去聚会，反而日子更加的好了,所以就更加的不去聚会。 而后来，儿子遇到了难处之后，儿子小的时候自己带着他去过古荡聚会，儿子就自己去了古荡聚会，给自己打电话说自己要信主了。后来儿子就被倪姊妹带到闲林小家来聚会，然后自己也来到这里聚会。 看着儿子好了起来，又不要信耶稣了。有一次儿子说自己去上班，自己跟神祷告说：如果儿子去上班，那说明主会救我；如果儿子没有去上班，那么儿子都来骗我，主不会救我了。然后让自己的丈夫去单位找儿子，儿子刚好没有在单位，就想着主不会救我了，而丈夫刚走，儿子就到了，前后相差不过5分钟。但自己就认为主不会救我了。所以过年的时候就不想去聚会，倪阿姨去探望，探望了几次，最后就骗姊妹说自己去宁波去了。后来倪姊妹就去家里探望，结果自己的谎言被穿帮了。后来想想自己这么不好，然后就想着自己真的要起来，自己不敢再离开主。然后今年就一直在闲林小家聚会。
- 自己之前遇到困难，就跌倒不去聚会，后来明白过来，就知道在困难当中也要明白有主的恩典，收取的是耶和华，赏赐的也是耶和华。现在自己儿子也改变了很多，也知道要信主，也有主日如果有时间的话就来聚会的心志，自己劝儿子不要走妈妈的老路，做一个敬畏神的人。 
*** 顾阿姨
- 09年得病，在这之前，妹妹家都是基督徒，妹妹的婆婆一来，就打开圣经给自己传福音，但自己不想听这个东西。得病后，查出来骨髓瘤，患病机率为十万分之一，最多只能活三年，当时骗子一片空白，大家来看望的时候，谁都不理，想着自己活不过去就完了。而妹夫给自己传福音，说你没有别的办法，只有信耶稣了，就教了自己一首诗歌。妹夫讲：如果你相信耶稣，你什么都不会怕。然后就自己想着，好吧，那我就相信吧。然后就做祷告，虽然当时也不知道什么是祷告，然后就祷告说主耶稣，我相信你，只有你能救我。
- 信了耶稣之后，心就平安了，心情也就好了，但是表面上说自己相信了，但是心里还是不太相信。后来就开始化疗，看着旁边几个人化疗着都死去了，但是自己知道自己是相信主的，主必定会救我的。而自己旁边一个19岁的小伙子，因为发烧，白血病，烧退不掉，亲戚们都去搞迷信，后来第7天，医生说这个小伙子可能会死掉，你要不离开这个病房？但是自己因为相信主，什么都不怕，就睡在小伙子的邻床。
- 化疗的时候，因为药物的原因，会麻痹神经，后来倪姊妹和萧山的弟兄去看望。弟兄姊妹们为妈妈、保姆和自己祷告，妈妈79岁，相信迷信，是一个老迷信。79岁的时候花了3000元去寺庙，但是祷告之后，妈妈有一个信心，主耶稣必定会救自己的女儿，然后就说自己什么都可以丢掉，就要自己的女儿。弟兄问：如果要信主，就举手，妈妈、保姆和自己都举手。但是自己丈夫却逃掉了。妈妈、保姆和自己都做了相信祷告。
- 后来就在经过倪姊妹在药江聚会，自己去聚会，丈夫开着车，然后自己上去聚会，丈夫不上去就在车子里面坐着。一年后，就来到了闲林小家。在药江聚会，就去了没几次。因着自己抽烟、喝酒，查出来癌症。然后自己就给他传福音，说你要相信耶稣，主耶稣已经救了我了，也一定救你。丈夫自己就因着这个病，在病房里面，肚子比较胀痛，走一走，转一转，这个屁放不出来，很难受，结果就祷告主，结果没几分钟，屁就放出来了。然后觉得主真灵，就给别人见证主。后来就去开刀，手术七个小时，非常的成功，到现在都没有复发。手术成功之后，病房安排在高干的旁边，可以看到西湖，病房里面还有沙发，别人以为这人有一些来头呢。这时候，丈夫有一些感动，知道手术的安排，医生的安排，病房的安排都是主亲自的安排。
- 来到闲林小家之后，后来就上楼来聚会了，因着病的原因，也不能抽烟，也不能喝酒。但是自己不知道什么原因，就是不愿意受洗。
*** 小顾阿姨
- 13年信主，妈妈信主几十年，有聚会也去听，信主还是慢慢来。
- 13年丈夫去世，后开始在杨家牌楼聚会，后去杨家牌楼聚会，13年12月28号受浸，后来闲林小家开始聚会
- 现在在杭州小女儿家里住，女儿，女婿都没有信，在绝世风情。聚会女儿全程接送；
*** 邵阿姨
- 老家周四祷告、探望都有负担，现在回老家，在闲林好像都没有担子了，这里很闲，没有老家那么忙碌；
- 家里面蒙主的恩典是全家都得救，敬虔的家庭
- 外甥女生病了，凭着信心祷告，病就好了；
- 丈夫在船上的见证
- 因为多次的祷告，神给了特别的恩典
*** 孙芬芬姊妹
- 13年4月份受浸，怀孕期间特别恩典
- 恩典很多，但读经祷告很少，能够感恩来到小家聚会。
- 妈妈现在在家，有信心带领归主
*** 蒋丽
- 365天 天天都有恩典
- 16年经历的大事：大学同学患癌症（感觉自己传福音的能力很差，但是这样的事情却是神来做工）、舅妈生病（每早晚为她祷告，表姐们放下工作都陪她，祷告转换方向为早日释放，两天后就走了，知道信和不信的人去的地方是不一样的）、小潘弟兄的事情（去富阳丧事聚会的时候就知道信耶稣的死之后要去哪里）
- 每天过马路都祷告，很怕过马路
- 刚开始的时候很害怕当主日学老师，但欣妍的一些懂事让自己的害怕没有了；后来带大班，然后小孩子们都很配合。他们虽然小，但是和世界上的孩子有一些区别。
*** 张珊迦
- 主日学的欣妍被自己成功拿下，成为一级小助手；觉得其他的小孩子比较危险的时候提醒老师；改造主日学的教室，引入一些书籍；
- 16年5月份爷爷去世，去世之前是被重症监护室，大家不能看望，以为大家都不要自己了。过年被医生活活过了八天。祷告不要被主接去，突然病倒，大家都没有心理准备。被救活过来之后，给大家一个心理准备，大家都知道爷爷年纪大了，要去世了；大家都在慢慢适应这个事实，大家慢慢在聊这个过程。后来爷爷去世了，没有失去的感觉，而是暂时的离别。
- 16年从阿里离职，离职后一个月在这里一直睡觉，睡成猪的样子；思考自己去做一些适合自己的事情；

*** 邵老弟兄
- 妈妈因为得病而相信耶稣
- 妈妈信主之后，还是去偶像的殿里面去玩过；自己慢性胃炎，身体不太好，生活没有力气，也去相信主
- 去聚会的时候，刚开始的时候信心非常的好，身体像长翅膀一样，很轻松，很清楚；唱诗歌257首
- 信主后，在丧事福音的时候，年轻人为主做工，抬棺材，路虽然远，但是有主的同在，心里很舒服，心里很愉快；在奉献的时候，心里都很喜乐；
- 之后教会里面的同工有嫉妒，因为负责的弟兄嫉妒另外一位弟兄的恩赐；请那位弟兄到自己这里来聚会，来做牧养的工作；负责弟兄不喜悦，就来有一些逼迫的工作；而有另一处教会来资助，那边的老弟兄曾经建立了七个教会，大家都非常的尊重他。后来负责的弟兄让并到五塘那边去。后来因着教会的分裂，自己就出来了；当时在那边吹中号的，在家里面的都会也是管帐的；之前教会里面不写帐；
- 来闲林之后，去过三自教会；自己感觉三自从真理方面没有走错路；地方教会在教义和讲道方面有一些极端；有一位朋友肠癌晚期，信耶稣之后，病有一些好转，但是有弟兄说如果你信心好，你不要吃药，老弟兄去劝这位姊妹可以吃点药。
- 两个女婿还没有信主，大女婿家里面都是拜偶像的，所以很抵挡；小女婿也不反对，但也不相信；
- 因着自己的相信，带领自己的妻子，丈母娘信主，大舅子都信主了、

*** 王伟斌弟兄
- 来闲林聚会已经一年的时间了，就站过一次讲台，周五的一次聚会；服侍比较少，主日学的服侍看到他们祷告非常的不容易。
- 一年感恩聚会情况比较正常；生活当中的一些经历，比较平淡，但也有一些的学习；上课之前祷告，但是只是停留在脑海当中；
- 婚姻方面长辈弟兄都会很操心，自己家乡的教会也很操心
- 教会里面的弟兄姊妹在信仰方面的交通，彼此的了解，可以不断的长进，在信仰的深度和学习方面

*** 曾一鸣弟兄
- 

*** 倪姊妹
- 撒上15:22节 自己对家里的弟兄不顺服，对基督的不顺服
- 13年六月份开始在闲林传福音，现在很多人来聚会；想想之前聚会的人很少，现在聚会人很多；别的小家都是买会所，我们小家自己房子买来；但自己内心骄傲，还将荣耀归给神；
- 闲林小家的饼杯问题不要跟着杭州教会走，而是要遵照主的喜悦；总要持守一饼一杯的真理；
- 乐乐掉到井里，然后被邻居给救起来；这才知道自己聚会不光是主日聚会，平时聚会也当用心，后来就开始起来；
- 但是得到了恩典却要忘记了恩典，后来乐乐又被拐卖了，神将乐乐放到民警的岗亭里面；
- 自己家里面所有的人都全是弟兄姊妹，都是蒙恩得救的；
- 自己觉得我为神做工，为什么担子这么大；后来才明白，做工若不为神做工，若是高举自己，不高举基督，一切都是枉然

*** 一鸣弟兄
- 

*** 秋波姊妹
- 生活平淡，但在平淡的生活里面来数算神的恩典 
****  家庭 -- 用爱去调和
- 自己和婆婆的关系，婆婆走一条不讨神喜悦的发财之路，最后婆婆和家里面的人关系都僵化了；后来因着子轩家庭的关系又重新再次建立起来；后来因着其他地方教会的一位弟兄告诉婆婆不要再做了，让她回去，神自己做工，自己没有做什么，借着弟兄的口将婆婆挽回；
- 回来之后，都显得尴尬，但是后来大家慢慢相处，慢慢彼此相爱
**** 工作 -- 用生命去做
- 从12年10月份开始转变做幼儿教育，到现在已经4个年头了。
- 15年9月到16年9月，带班，很多问题，家长群里面也有太多的问题
- 16年，生源都是口碑相传，不需要宣传；孩子一遇到问题我们就会去祷告，孩子发烧祷告
- 从生命影响生命；
**** 服侍方面 -- 学着去做
- 15年3月份来到闲林小家聚会；当是一遍的圣经都没有读完，祷告也只是停在口头上
- 从开始看孩子，后来就开始有教材，老师们的牧养工作开始。
- 后来主日学的老师们开始多了起来，孩子们也多了起来，就开始了主日学的小班，小班的环境布置，老师们的装备
**** 属灵方面 
- 16年6月份的时候，心里很软弱，弟兄也比较软弱，长辈给了几首诗歌，每天上班都唱573首，因为每一天都需要面对家长和孩子们；诗篇23篇，每天晚上也都唱
- 读经16年8月22号读完一遍；开始读第二遍的时候，看到环境有一些好转，就会有一些懒惰；

*** 陈工弟兄
- 感觉自己跟神就是若即若离的一种感觉；

*** 薛姊妹
- 今年的顺服功课学的不少；
- 看了一年的圣经，看问题会从另外一个角度来考虑；
- 圣经来教导孩子，不听父母就是犯罪
