#+STARTUP: showall
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+LANGUAGE: zh-CN
#+OPTIONS:   ^:{}
#+TITLE: 经历神，生命更加长进
#+TAGS: 
#+DATE: 2017-03- 4
** 读经
- 路10:38-42
- 约11：1-6、11:17-44
- 约12:1-3
** 背景介绍
- 主耶稣在约旦河附近，约翰施洗的地方；10:40
- 主耶稣到伯大尼大约需要一天的时间
- 有可能送信的人到主耶稣那里的时候，拉撒路已经死了
- 当时不是冬天，逾越节近了，正月十四，大概阳历的三月份
- 和合本圣经当中最短的一句话：耶稣哭了约11：35
** 为什么主耶稣要停留两天
- 为要让神得着荣耀
- 让门徒们更加相信
- 让犹太人更加相信
- 给这家人带来转机
这也是说到我们弟兄姊妹信耶稣的经历；经常会有弟兄姊妹说：我祷告了，主不听我的祷告；弟兄姊妹，一方面是因着我们带着罪恶在祷告，神是圣洁的，必不听我们的祷告；另一方面，是我们太着急了，神一直在做工，只是我们没有等到做工果效的那一天我们就放弃了；雅4：7-8节里面教导我们应当忍耐，虽然这是指着我们主的再来讲的，也是对我们的属灵生活的一个真实的写照。
** 因着复活的经历这家人的改变
*** 拉撒路的改变 -- 重新起来跟从主
拉撒路这一家可能是有一些地位的人，因为19节里面讲到说有很多的犹太人去看望马大和马利亚；一个人的去世之后，参加他葬礼的人是他这一生的写照。如果一个人去世了，没有一个人来参加葬礼，那说明这个人就是失败的一生；如果有千千万万的人来参加，说明这个人的一生是荣耀的一生。像李慕圣、小攀弟兄。
路加福音10:38-42节记载着耶稣曾经在马大家里做客，但是这个时候却没有拉撒路，我们可以看到拉撒路并不热心听主的道，也不热心去参加服侍的工作。我们不知道他在哪里；但是当他复活之后，因着从死里复活的经历，在约12：2节里面我们看到，他却同耶稣在一起坐席。

经历过死里复活，他的人生开始转变，之前不认为主耶稣是宝贵，现在却以主耶稣为至宝；之前不认为听道是有益处的，现在却是一直跟从主；之前一边信主，一边作自己的事情，现在却愿意完全为主而活着。

今天，教会当中有很多这样的弟兄姊妹，我们不知道他在哪里，我们不知道他们因着什么事情而不来聚会；但当有一天，神亲自临到他的时候，他对神有了第一手经历的时候，他就被主所改变，他就被主所得着，重新起来跟从主，成为耶稣基督的见证人；

弟兄姊妹，另外一方面，我们也看到一个人不热心做工，不将自己全身心的摆上，主也是爱他的；永远不要以某个人在主面前多么热心，多么做工为衡量基督徒是否爱主的标准；那样的门徒不一定是主爱的；并且我们也没有资格与衡量别人爱主的心；
*** 马大的改变-- 更加愿意侍奉
在路加福音10：38-42节里面记载着马大因着伺候的事多，心里忙乱，思虑烦乱。在约12：2节里面我们看到这个时候，马大伺候主耶稣和门徒及其他的人，这个时候她改变，她不再思虑烦乱，知道侍奉不是凭着自己，若是自己在那里服侍神，真的是太累了；当我们的侍奉遇到了难处的时候，思虑烦乱的时候，一定要回转到主的面前，或交通在弟兄姊妹面前；不要给仇敌留下空子，给自己和教会带来损失。侍奉神一定不能凭着自己。
*** 马利亚的改变-- 更加彻底奉献
在路加福音10：38-42节里面记载着马利亚安静的在主面前听道，而在约12：3节里面我们看到，她将自己最珍贵的东西拿出来奉献给主；

我们看到马利亚之前是多么爱主的一位姊妹，相信主耶稣就是那位荣耀的基督，也常常听主耶稣讲道，生命在不断的改变，不断的长进；但是心里面始终有一个过不去的东西，那就是她最珍贵的香膏，一直没有拿出来给主；她心里一直有一个不愿意的地方，那就是不愿意将自己的香膏给主，那是她最珍贵的东西，是她嫁人的时候所预备；那是她所有的爱情，一个女人一生最宝贵，最珍视的；而今，她做出一个非常重要的决定，不是凭着自己，乃是因着经历了主耶稣，对主耶稣有了更加深入的认识，知道这就是她一生所爱的，一生愿意为他而活的；她将自己最宝贵的香膏打碎，将自己的爱情倾倒在主的面前，就生发出香膏的香气；

讲夏老弟兄的见证；

奉献是一个人走主路的必须条件，奉献是圣洁的，是神所喜悦的，并且也是理所当然的；最占你心思的东西，任何阻止你爱主的事物，都是神所不喜悦的；有的弟兄姊妹也许会讲：弟兄怎么可以这么讲呢？如果我爱我的孩子，我因着我的孩子不能来聚会，读经、祷告，那孩子是神所不喜悦的么？弟兄姊妹，如果你真爱你的孩子，你就会常常为他祷告，而不是一味的关心和爱护，而是真正的将孩子交在神，在孩子成长的同事时，你的属灵生命也在长进。

** 信心和行为，哪个在前
当两个姊妹见以主耶稣的第一句话：都是“主啊，你若早在这里，我兄弟必不死 ”
- 她们的信心停留在主耶稣在旁边能够阻止弟兄的死，如果主耶稣不在这里是他兄弟死的原因。
- 如果马大真的相信主耶稣能让她兄弟复活，就不会说出必定臭了这句话；
- 话语的理解与实际是两回事，马大话说的非常的好，对神的理解也是非常真实，但主耶稣立刻让他兄弟复活，她却没有这个看见
- 信心没有行为是死的，光有行为，没有信心是无用的；

弟兄姊妹，小弟兄需要劝戒各位弟兄姊妹，有的事情虽然不是你能左右的，但是是你可以改变了，不要看人过于高看神；凡事仰望，多有祷告，多有经历，这样才能不断的长进。
讲张弟兄的见证；

持守见证，持守真道，真等主来！！

如果主耶稣不来行这个神迹，那么会有什么另外的效果呢？
